name: dxjoke Tectonic Docker

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Compile
        run: docker run --mount src=GITHUB_WORKSPACE/travis-ci-latex-pdf/src,target=/usr/src/tex,type=bind dxjoke/tectonic-docker /bin/sh -c "tectonic main.tex"
